[workspace]
authors = ["Andrew Sazonov <andrew.sazonov@icloud.com>"]
channels = ["conda-forge"]
name = "peasy-app"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
copier = ">=9.11.1,<10"
